name: Deploy to production on manual trigger
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate CNAME
        run: touch public/CNAME && echo "docs.hpc.taltech.ee" > public/CNAME
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'public/'
          destination-github-username: 'TalTech-HPC-Centre'
          destination-repository-name: 'user-guides-production'
          user-email: hpc-actions@taltech.ee
          target-branch: main
          target-directory: public